-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/kjjzynspdwybjudipend/sql)

CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  message TEXT,
  project_type TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anyone to insert (Anon access)
CREATE POLICY "Allow anonymous inserts" ON leads
FOR INSERT 
WITH CHECK (true);

-- Optional: Create a policy to allow authenticated users (you) to see the leads
CREATE POLICY "Allow authenticated selects" ON leads
FOR SELECT
TO authenticated
USING (true);